### ISSUE TITLE
dash-leaflet Map() CSS Issue

### ISSUE THREAD

**Issue by buckeye17** [thedirtyfew/dash-leaflet#73]
I've discovered that if a `dl.Map()` element is contained in an html element that has `display: none` during the page's initial load, then when the html element is revealed, the `dl.Map()` will be broken, appearing as shown below.  So long as the initial DOM has the `dl.Map()` element visible, any subsequent changes to visibility work fine.

![image](https://user-images.githubusercontent.com/17264335/106821366-ff31d100-664a-11eb-8607-4e045aa17836.png)

**Comment by emilhe** [comment]
What version are you running?

**Comment by emilhe** [comment]
This is a known bug. If the map is not visible on initial render, it won't render properly.

**Comment by prl900** [comment]
This might be related as I'm seeing a similar map rendering problem map. However, in my case, the error happens when the map is embedded in a dash-bootstrap tab.

Here is a simple program that reproduces the error:

```
import dash
import dash_leaflet as dl
import dash_bootstrap_components as dbc
from dash import html
from dash import dcc

app = dash.Dash(external_stylesheets=[dbc.themes.YETI])
#app = dash.Dash()

app.layout = dbc.Container([
    dbc.Row([
        dbc.Tabs([
            dbc.Tab(
                dbc.Card(
                    dbc.CardBody([
                        html.P("This is tab 1!", className="card-text"),
                        dbc.Row([
                            dbc.Col(dl.Map(dl.TileLayer(), center=[-35.4,149.2], zoom=10), style={'height': '60vh', 'margin': "auto", "display": "block", "position": "relative"}, width=12, className='mt-1'),
                        ]),
                    ]), 
                className="mt-3"), 
            label="Floodings"),
        ])
    ])
], fluid=True)

if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=8080, debug=True, use_reloader=False)
```

Changing the commented line to the one that doesn't load the Bootstrap YETI theme solves the rendering problem, so I wonder if there are CSS definitions messing up the map rendering functionality.

**Comment by giadasp** [comment]
How this issue can be solved? 
I tried to not import the bootstrap stylesheet and to re-render only the layers (TileLayer and MarkerClusterGroup)   but still it does not work. Only manually resizing the window solves the problem.
Re-rendering the map everytime I switch a tab or I hide/display a div is not efficient.
I hope you can help me.
Thank you.
Giada

**Comment by MonkeyChap** [comment]
I'm getting this problem too. Was it ever fixed ?

**Comment by tobiasmllr** [comment]
I have the same problem. Can a re-render be forced somehow when the tab is loaded for the first time?

**Comment by raphaelleroffo** [comment]
I am also facing the same rendering issue within a Bootstrap tab - will be keen to hear about any update on this!

**Comment by Duvancho321** [comment]
change `dbc.Tabs` to `dcc.Tabs`. you can try modify the style of tabs with:

```
style = {'width': '40%',
         'height': '8px',
         'line-height': '0px' ,
         'line-width': '0px',
         'margin-bottom': '40px'}
```

**Comment by emilhe** [comment]
A new `invalidateSize` property has been added to the `Map` component as part of the `1.0.4` release. Every time you set it to a (new) truthful value, the map size is invalidated thus solving this issue. Here is a small example,

```
import dash
import dash_leaflet as dl
from dash import html, Output, Input

app = dash.Dash(prevent_initial_callbacks=True)
app.layout = html.Div(
    [
        html.Div(
            dl.Map(dl.TileLayer(), center=[56, 10], zoom=6, style={'height': '50vh'}, id="map"),
            style=dict(display="none"),
            id="container"),
        html.Button("Show", id="btn")
    ],
)


@app.callback(Output("container", "style"),
              Output("map", "uirevision"),
              Input("btn", "n_clicks"))
def show(n_clicks):
    return dict(display="block"), n_clicks


if __name__ == '__main__':
    app.run_server()

```

**Comment by MateoLostanlen** [comment]
@emilhe I've just tried your code but the display problem is still there. Or maybe I didn't understand. Can you explain how this solves the problem?

![image](https://github.com/emilhe/dash-leaflet/assets/17944639/713bddd0-68c7-4ac4-bb70-32a9ccc69edf)

**Comment by emilhe** [comment]
Hi Mateo,

Could you post the code that isn't working?

\emher

**Comment by henrygsys** [comment]
I was facing this issue and I had a few problems recreating this solution because i am generating my map via a call back and generating dynamic data based upon a user selected value for a location. I solved by splitting into two callbacks, one to create the figure template, and the second to provide the data.

@emilhe one issue that i am is facing, is that the map centre does not update as i pass new coordinates via the callback, it remains on the location that was rendered when the map was first loaded. Is this a known issue and is there a fix for this?

   ```
 html.Div(
        children=[],
        style=dict(display="none"),
        id="container", className="container")

@dash.callback(Output("container", "style"),
              Output("container", "children"),
              Input("custom-select", "value"))
def show(input):
    center = return_map_coordinates(input)
    return dict(display="block"),\
        dl.Map(center=[float(center[0]), float(center[1])], zoom=4, style={'height': '50vh'}, id="map_")

@dash.callback(Output("map_", "invalidateSize"),
              Output("map_", "children"),
              Input("custom-select", "value"))
def show(input):
    
    map_children = [
        *markers,
        dl.LayersControl(
        [dl.BaseLayer(dl.TileLayer(url=value.get("url_template"), attribution=value.get("attribution")),
                      name=key, checked=key == list(LEAFLET_BASE_LAYERS.keys())[0])
         for key, value in LEAFLET_BASE_LAYERS.items()]
            +
            [dl.Overlay(dl.LayerGroup(geojson), name="geojson", checked=True)]
            +
            [dl.Overlay(dl.LayerGroup(wms_layer), name="WMS", checked=False)],
            id="lc"
        )]

    return input, map_children 

```

**Comment by Akilditu** [comment]
Hi @emilhe , 

Whole is a too long to be copied here because it's a multi pages app but I don't get why it's not actually working (map still having a display bug) even though `invalidateSize` seems properly implemented. 

Here the actual callback : 

```
@app.callback(
    [
        Output("login_modal", "is_open"),
        Output("login_storage", "data"),
        Output("form_feedback_area", "children"),
        Output("login_zoom_and_center", "data"),
        Output("hp_map", "style"),
        Output("map", "invalidateSize"),
        Output("user_headers", "data"),
        Output("devices_data_storage", "data"),
        Output("site_devices_data_storage", "data"),
        Output("sites_data", "data"),
        Output("sites_markers_div", "children"),
        Output("user_credentials", "data"),

    ],
    Input("send_form_button", "n_clicks"),
    [
        State("username_input", "value"),
        State("password_input", "value"),
        State("login_storage", "data"),
        State("map", "center"),
        State("map", "zoom"),
    ],
)
def manage_login_modal(n_clicks, username, password, login_storage, current_center, current_zoom):
    """
    --- Managing the login modal ---

    This callback is triggered by clicks on the connection button in the login modal and also takes as input the user-
    name, as well as the password, entered by the user via the login form.

    It updates the following output:

    - the "is_open" attribute of the login modal, a boolean which indicates whether the modal is open or not;

    - the "children" attribute of the HTML Div that stores feedback associated with user's input in the login form;

    - the "data" attribute of the dcc.Store component which saves site devices data, fetched from the API once the user
    successfully logs in;

    - the "center" and "zoom" attributes of the map object, so that the user directly ends up on the map zoomed on his /
    her department after logging in (this relies on the center_lat, center_lon and zoom fields in the login_correspon-
    dences.csv file).

    The logic is the following:

    - the callback runs a series of checks on the username / password pair;

    - as soon as one check is not satisfied, True is returned for the "is_open" attribute of the login modal, such that
    it remains open and arbitrary values are returned for the other outputs;

    - if all checks are successful, the login modal is closed (by returning False for the "is_open" attribute of the lo-
    gin modal), site devices data is fetched from the API and the right outputs are returned
    """
    ctx = dash.callback_context

    if not ctx.triggered:
        raise PreventUpdate

    # The modal is opened and other outputs are updated with arbitrary values if no click has been registered on the
    # connection button yet (the user arrives on the page)
    if n_clicks is None:
        return [
            True,
            {"login": "no"},
            None,
            {"center": [10, 10], "zoom": 3},
            {"display": "none"},
            dash.no_update,
            dash.no_update,
            dash.no_update,
            dash.no_update,
            dash.no_update,
            dash.no_update,
            dash.no_update,

        ]

    # if login_storage['login'] == 'yes':
    #     return False, {'login': 'yes'}, None, {'center': current_center, 'zoom': current_zoom}, {}

    else:
        # We instantiate the form feedback output
        form_feedback = [dcc.Markdown("---")]

        # First check verifies whether both a username and a password have been provided
        if username is None or password is None or len(username) == 0 or len(password) == 0:
            # If either the username or the password is missing, the condition is verified

            # We add the appropriate feedback
            form_feedback.append(html.P("Il semble qu'il manque votre nom d'utilisateur et/ou votre mot de passe."))

            # The login modal remains open; other outputs are updated with arbitrary values
            return [
                True,
                {"login": "no"},
                form_feedback,
                {"center": [10, 10], "zoom": 3},
                {"display": "none"},
                dash.no_update,
                dash.no_update,
                dash.no_update,
                dash.no_update,
                dash.no_update,
                dash.no_update,
                dash.no_update,
            ]

        else:
            # This is the route of the API that we are going to use for the credential check
            try:
                client = Client(cfg.API_URL, username, password)
                # All checks are successful and we add the appropriate feedback
                # (although the login modal does not remain open long enough for it to be readable by the user)
                form_feedback.append(html.P("Vous êtes connecté, bienvenue sur la plateforme Pyronear !"))

                # Based on the user's credentials, we request the set of relevant devices
                response_devices = requests.get(f"{cfg.API_URL}/devices/", headers=client.headers)

                # We also update the site_devices dictionary, restricting it to the user's scope
                response_sites = client.get_sites().json()
                site_devices = {site["name"]: client.get_site_devices(site["id"]).json() for site in response_sites}

                # Eventually, we update the markers on the map
                sites_markers_div_children = dl.GeoJSON(
                    children=build_sites_markers(sites_with_live_alerts=[], camera_positions=response_sites),
                    id="sites_markers",
                )

                # We sum the latitudes and longitudes of the sites that are in the user's scope
                latitudes = 0
                longitudes = 0
                for site in response_sites:
                    latitudes += site["lat"]
                    longitudes += site["lon"]

                # We deduce the mid-point around which we want to center the map
                lat = latitudes / len(response_sites)
                lon = longitudes / len(response_sites)

                # We set the zoom level for the map display at 9 by default
                zoom = 9

                # The login modal is closed and the appropriate outputs are returned
                return [
                    False,
                    {"login": "yes"},
                    form_feedback,
                    {"center": [lat, lon], "zoom": zoom},
                    dict(display="block"),
                    n_clicks,
                    client.headers,
                    response_devices.json(),
                    site_devices,
                    response_sites,
                    sites_markers_div_children,
                    {"username": username, "password": password},
                ]

            except Exception:
                # This if statement is verified if credentials are invalid
                form_feedback.append(html.P("Nom d'utilisateur et/ou mot de passe erroné."))
                # The login modal remains open; other outputs are updated with arbitrary values
                return [
                    True,
                    {"login": "no"},
                    form_feedback,
                    {"center": [10, 10], "zoom": 3},
                    {"display": "none"},
                    dash.no_update,
                    dash.no_update,
                    dash.no_update,
                    dash.no_update,
                    dash.no_update,
                    dash.no_update,
                    dash.no_update,
                    dash.no_update,
                ]


@app.callback(Output("login_background", "children"), Output("main_navbar", "style"), Input("login_modal", "is_open"))
def clean_login_background(is_modal_opened):
    """
    --- Erasing the login backrgound image when credentials are validated ---

    This callback is triggered by the login modal being closed, ie. indirectly by the user entering a valid username /
    password pair and removes the login background image from the homepage layout.
    """
    if is_modal_opened:
        raise PreventUpdate

    else:
        return "", {}
```
The div where the map is hidden : 

```
# Map object added here
html.Div(build_alerts_map(), id="hp_map", style={"display": "none"}),
```

And Finally the Map objet : 

```
def build_alerts_map():
    """
    The following function mobilises functions defined hereabove or in the utils module to
    instantiate and return a dl.Map object, corresponding to the "Alerts and Infrastructure" view.
    """
    map_object = dl.Map(
        center=[44.73, 4.27],  # Determines the point around which the map is centered
        zoom=9,  # Determines the initial level of zoom around the center point
        children=[
            dl.TileLayer(id="tile_layer"),
            build_departments_geojson(),
            build_filters_object(map_type="alerts"),
            build_legend_box(map_type="alerts"),
            html.Div(
                id="sites_markers_div",
                children=dl.GeoJSON(
                    children=build_sites_markers(sites_with_live_alerts=[]), id="sites_markers"
                ),
            ),
            dl.LayerGroup(id="vision_polygons"),
            html.Div(id="live_alerts_marker"),
            html.Div(id="live_alert_header_btn"),
            html.Div(id="fire_markers_alerts"),
        ],  # Will contain the past fire markers of the alerts map
        style=map_style,  # Reminder: map_style is imported from utils.py
        id="map",
    )
```

Thanks a lot for your help and do not hesitate if you need more insights 🙏
